### ISSUE TITLE
Support type in array

### ISSUE THREAD

**Issue by jandudulski** [monterail/gate#1]
e.g. `required :field, :Array[:String]`

And more complicated with structure inside.

**Comment by jcieslar** [comment]
structure inside - it would be great!

**Comment by jandudulski** [comment]
Api proposal:

``` ruby
gate = Gate.rules do
  required :id, :Integer
  required :message do
    required :ids, Collection: :Integer 
    optional :structures, :Collection do
      required :author
    end
  end
end
```

@jcieslar WDYT?

**Comment by jcieslar** [comment]
As I understand it correctly inside `optional :structures, :Collection do` we define collection structure, right? Sample payload e.g.: 

``` ruby
{
  id: 123,
  message: {
    ids: [1,2,3],
    structures: [
      { author: 'Jan' }, 
      { author: 'Jakub' }
    ]
  }
}
```

**Comment by jandudulski** [comment]
@jcieslar that's right. I'm trying to find out the most convenient way for usage :)

**Comment by jandudulski** [comment]
Alternative:

``` ruby
gate = Gate.rules do
  required :id, :Integer
  required :message do
    required :ids, :IntegerCollection 
    optional :structures, :Collection do
      required :author
    end
  end
end
```

or

``` ruby
gate = Gate.rules do
  required :id, :Integer
  required :message do
    required :ids, :Strings 
    optional :structures, :Collection do
      required :author
    end
  end
end
```

**Comment by teamon** [comment]
why not 

``` ruby
required :id, Integer
required :message do
  required :ids, Array[Integer]
  optional :structured, Array do
    required :name, String
  end
end

```

 ?

**Comment by jandudulski** [comment]
@teamon Gate uses symbols here, not classes.

**Comment by teamon** [comment]
- CamelCase symbols look strange
- Hash/Map is also a "Collection" so this might be missleading
- please have custom types extensibility in mind (think Date, UUID, Structs etc)

**Comment by jcieslar** [comment]
I like your first proposition: `Collection: :Integer` and `:Collection`

Also we need to support collection inside collection.

**Comment by jandudulski** [comment]
> CamelCase symbols look strange

Matter of taste ;)

> Hash/Map is also a "Collection" so this might be missleading

Good point.

> please have custom types extensibility in mind (think Date, UUID, Structs etc) 

Probably I have to rethink implementation :baby:

**Comment by jandudulski** [comment]
> Also we need to support collection inside collection.

Riiiight.

``` ruby
optional :deep, Collection: { Collection: { Collection: :Integer } }
```

Doesn't feel right but such structures should be supported. Meh :hammer:
