### ISSUE TITLE
Requirements and API design

### ISSUE THREAD

**Issue by jandudulski** [monterail/gate#4]
Following discussion from #1 

This is list of requirements which I am aware of (both supported and nice to have):
- required / optional
- basic types casting (string, integer, decimal, etc)
- extensibility for custom types
- nested structures definitions
- arrays with definition for values (both structures and simple ones), so e.g. array with arrays with arrays with structure
- allow/not allow nil values

Anything else in mind? @teamon @jcieslar

**Comment by jcieslar** [comment]
Looks good for me. Are we really need `extensibility for custom types`?

**Comment by teamon** [comment]
This is a question where should validation really happen.

**Comment by jandudulski** [comment]
> This is a question where should validation really happen.

Depends what kind of validation do you mean? IMHO gate should be kind of type validator, nothing really related to business logic.

**Comment by teamon** [comment]
If so, do you treat UUID as type or business logic? ;)

**Comment by jandudulski** [comment]
Type

**Comment by teamon** [comment]
So we need extensibility, i.e IP address is also a type etc.

**Comment by teamon** [comment]
And btw, there is also a NonEmptyString type ;)

**Comment by jandudulski** [comment]
``` ruby
Gate.rules do
  required :values, :Array, deep_level: 2, nested_type: :Integer
  required :structures, :Array, deep_level: 2 do
    required :nested_id
  end
end

{
  values: [
    ["1", "2", "3"],
    ["4", "5", "6"]
  ],
  structures: [
    [{ nested_id: "42" }, { nested_id: "23" }],
    [{ nested_id: "18" }, { nested_id: "99" }]
  ]
}
```
