### ISSUE TITLE
Support for more than one parameter type 

### ISSUE THREAD

**Issue by MadMadlen** [monterail/gate#5]
It would be great to have support for more than one type of parameter in Gate rules.

**Comment by teamon** [comment]
Sounds like [Either type](http://danielwestheide.com/blog/2013/01/02/the-neophytes-guide-to-scala-part-7-the-either-type.html) or more generally [ADT](https://wiki.haskell.org/Algebraic_data_type)

**Comment by jcieslar** [comment]
Gate could also allow to have no type definition and custom types.

**Comment by teamon** [comment]
True. (Sounds like [Any](http://www.scala-lang.org/api/2.7.2/scala/Any.html))

**Comment by jcieslar** [comment]
We added support for `Any` but it still would be nice to have: `support for more than one type of parameter`

**Comment by jandudulski** [comment]
@MadMadlen @jcieslar do you still remember what was the use case for that?

**Comment by jcieslar** [comment]
@jandudulski I do not remember. I'm guessing, maybe we would like to have support for two data type for one parameter. /cc @MadMadlen
